# Generated by Django 5.1.1 on 2024-09-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='method')),
                ('path', models.CharField(max_length=255, verbose_name='path')),
                ('status_code', models.CharField(max_length=3, verbose_name='status_code')),
                ('user_agent', models.CharField(max_length=255, verbose_name='user_agent')),
                ('querystring', models.TextField(null=True, verbose_name='querystring')),
                ('request_body', models.TextField(null=True, verbose_name='request_body')),
                ('level', models.CharField(max_length=10, verbose_name='level')),
                ('message', models.TextField(verbose_name='message')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('exception', models.TextField(null=True, verbose_name='exception')),
                ('traceback', models.TextField(null=True, verbose_name='traceback')),
                ('server_ip', models.GenericIPAddressField(verbose_name='server_ip')),
                ('client_ip', models.GenericIPAddressField(verbose_name='client_ip')),
            ],
        ),
    ]
